---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/9/17 20:19
---
local rh = RHelper:new()
local bps = 0
local prevpos = {entity.get_x(player.id()),entity.get_z(player.id())}
local json_config = {Values = {}}

local autotogglemode
local autojump
local safepitchenable
local safepitch = 86
local speedenable
local customrotation
local speed
local tick = 0
local ScaffoldSpeedFix
local rotationfallcheck
local towerwarnning
local customspeed
local customspeedspeed2
local customspeedspeed
local customspeedjumpygroundspeed
local customspeedjumpyairspeed
local nowspeed = 0
local scaffoldtowertoggle = {false,0}
local supertick = 0
local boostspeedtick = {0,0,true}
local boosttickstop
local boosttick
local grimunfairrotationmovefix
local grimunfairrotationbpscheck ={false,""}
local grimunfairrotationhasjump = false
local disablelocky
local disablelockytick = 0
local deafultspeedmode
local alternativejump
local smartgrimsnap
local quickmacrotellytick = 0
local heypixeltellytick = 0
local heypixeltellygroundstate = false
local towermode
local hypixeltowerstate = false
local hypixeltowertick = {0,0,false}
local moonluatowerticks = 0
local moonluatower = false
local flagdetect_lastpreangle = {0,0}
local flagdetect_lastppreangle = {0,0}
function getName()
    return "Scaffold Helper"
end

function init_script()
    math.randomseed(os.time())
    rh:modules_reload()
    module_manager.set_description(getName(),"[By RenShen] Scaffold Fixed")

    module_manager.register_label(getName(),"-------------AutoToggle-------------")
    autotogglemode = module_manager.register_mode(getName(),"Mode",{"Normal","Speed","ReEnable","OnFalldown","Heypixel Telly","Quick macro"},"Heypixel Telly")
    autojump = module_manager.register_mode(getName(),"Autojump",{"Disabled","Normal","OnEdge","Parkour"},"Disabled")
    safepitchenable = module_manager.register_boolean(getName(),"Safe Pitch",true)

    module_manager.register_label(getName(),"-------------Hypixel Bypass-------------")
    
    module_manager.register_label(getName(),"Custom Speed")
    speedenable = module_manager.register_boolean(getName(),"Scaffold Speed",false)
    speed = module_manager.register_text(getName(),"Speed","0.1165")
    
    module_manager.register_label(getName(),"Custom Rotation")
    customrotation = module_manager.register_mode(getName(),"Custom Rotation",{"Disabled","HypixelBackward","HypixelAdaptive","Godbridge","Novoline","Snap","Super","Grim Unfair","Hypixel Unfair"},"Disabled")
    rotationfallcheck = module_manager.register_boolean(getName(),"Clutch Check",true)
    grimunfairrotationmovefix = module_manager.register_boolean(getName(),"Grim Unfair Movement Fix",true)

    module_manager.register_label(getName(),"BPS Override")
    customspeed = module_manager.register_mode(getName(),"BPS Mode",{"Disable","Custom","Random","Add","Boost","Heypixel"},"Disable")
    deafultspeedmode = module_manager.register_mode(getName(),"Default Speed Mode",{"Alternative","Watchdog"},"Watchdog")
    customspeedspeed = module_manager.register_text(getName(),"Speed","5.29")
    customspeedspeed2 = module_manager.register_text(getName(),"Speed 2","8.8")
    customspeedjumpygroundspeed = module_manager.register_text(getName(),"JumpY Ground Speed(<0 = disabled)","0.01")
    customspeedjumpyairspeed = module_manager.register_text(getName(),"JumpY Air Speed(<0 = disabled)","5.78")
    boosttick = module_manager.register_text(getName(),"Boost Tick","10")
    boosttickstop = module_manager.register_text(getName(),"Boost Wait Tick","0")

    module_manager.register_label(getName(),"-------------Misc-------------")
    towermode = module_manager.register_mode(getName(),"Tower",{"None","Hypixel","Heypixel","Moon Lua"},"Moon Lua")
    alternativejump = module_manager.register_boolean(getName(),"Alternative Jump",true)
    ScaffoldSpeedFix = module_manager.register_boolean(getName(),"Scaffold Priority Fix",true)
    smartgrimsnap = module_manager.register_boolean(getName(),"Smart Grim Snap Sprint",false)
    towerwarnning = module_manager.register_boolean(getName(),"Tower Warnning",false)
    disablelocky = module_manager.register_text(getName(),"Locked MotionY(<0 = disabled)","-1")
    client.register_command("helper_config",{})
    rh:config_init(json_config,getName())
    function on_pre_update()
        rh:modules_reloadtoggled(on_module_toggled)
        -- for key, _ in pairs(moduleslist) do
        --     if moduleslist[key] ~= module_manager.get_state(key) then
        --         on_module_toggled(key,module_manager.get_state(key))
        --     end
        --     moduleslist[key] = module_manager.get_state(key)
        -- end
        if module_manager.get_state("scaffold") then
            local function setspeed(speed)
                --player.set_speed(speed)
                --player.message(bps)
                for key, value in ipairs(module_manager.get_values("Scaffold")) do
                    if value:get_name() == "Actually Speed" then
                        value:set_double(speed)
                    end
                end
            end
            if ScaffoldSpeedFix:get_boolean() and input.is_key_down(module_manager.get_key("Scaffold")) then
                rh:setmodulevalue("Scaffold","Tower",false,"boolean")
                module_manager.disable("Speed")
            end
            if customspeed:get_string() ~= "Disable" and customspeed:get_string() ~= "Heypixel" then
                rh:setmodulevalue("scaffold","Speed Control","Manual","string")
                local defaultspeed = 4.27
                local maxs = math.max(rh:tonumber(customspeedspeed:get_string()) or defaultspeed,rh:tonumber(customspeedspeed2:get_string()) or defaultspeed)
                local mins = math.min(rh:tonumber(customspeedspeed:get_string()) or defaultspeed,rh:tonumber(customspeedspeed2:get_string()) or defaultspeed)
                if customspeed:get_string() == "Custom" then
                    setspeed(rh:tonumber(customspeedspeed:get_string()) or defaultspeed)
                end
                if customspeed:get_string() == "Random" then
                    setspeed(math.random(mins*10000,maxs*10000)/10000)
                end
                if customspeed:get_string() == "Add" then
                    setspeed(mins + nowspeed)
                    if mins + nowspeed > maxs then
                        nowspeed = 0
                    end
                    nowspeed = nowspeed + 0.01
                end
                if customspeed:get_string() == "Boost" and not input.is_key_down(57) then
                    local maxspeed = 7.5
                    local speed1 = rh:tonumber(customspeedspeed:get_string())
                    local speed2 = rh:tonumber(customspeedspeed2:get_string())

                    setspeed(speed1)
                    if boostspeedtick[1] >= rh:tonumber(boosttick:get_string())  and player.get_speed() > 0 then
                        boostspeedtick[1] = boostspeedtick[1] >= rh:tonumber(boosttick:get_string()) + rh:tonumber(boosttickstop:get_string()) and 0 or boostspeedtick[1]
                        boostspeedtick[2] = boostspeedtick[2] + 0.35
                        if speed2 >= maxspeed then
                            local rspeed = rh:tonumber(customspeedspeed2:get_string())
                            speed2 = maxspeed + (rspeed - maxspeed)*math.min(boostspeedtick[2],1)
                        end
                        setspeed(speed2)
                    end
                    if not player.on_ground() or input.is_key_down(57) then
                        setspeed(speed1)
                    end
                end
                if rh:tonumber(customspeedjumpygroundspeed:get_string()) >= 0 and input.is_key_down(57) then
                    setspeed(player.on_ground() and rh:tonumber(customspeedjumpygroundspeed:get_string()) or rh:tonumber(customspeedjumpyairspeed:get_string()))
                end
                if (player.get_speed() <= 0.11 or math.abs(player.moveInput():move_forward()) + math.abs(player.moveInput():move_strafe()) == 0) and not input.is_key_down(57) then
                    rh:setmodulevalue("scaffold","sprint mode","None","string")
                else
                    rh:setmodulevalue("scaffold","sprint mode",deafultspeedmode:get_string(),"string")
                end
            end
            if customspeed:get_string() == "Heypixel" then
                setspeed(rh:tonumber(customspeedspeed:get_string()))
                rh:setmodulevalue("scaffold","sprint mode",input.is_key_down(57) and "None" or "Vanilla","string")
                rh:setmodulevalue("scaffold","Speed Control",input.is_key_down(57) and "Manual" or "None","string")
                rh:setmodulevalue("sprint","mode",input.is_key_down(57) and "Basic" or "Omni","string")
                rh:setmodulevalue("strafefix","fix mode","Strict","string")
                if rh:module_state("autotoggle") and rh:module_state("scaffoldhelper") then
                    rh:setmodulevalue("scaffold","Speed Control","Smart","string")
                    rh:setmodulevalue("strafefix","fix mode","Basic","string")
                end
                if input.is_key_down(57) and rh:module_state("rspeed") and rh:getmodulevalue("rspeed","mode") == "Heypixel" then
                    rh:setmodulevalue("scaffold","Speed Control","None","String")
                end
            end
            if towermode:get_string() == "Hypixel" then
                local yaw_segment = math.floor(((player.angles():get_yaw() % 360) + 11.25) / 22.5) 
                -- if scaffoldtowertoggle[1] == false and (player.facing() == "NORTH" or player.facing() == "SOUTH") and yaw_segment/8%1 ~= 0.75 and yaw_segment/8%1 ~= 0.25 then
                --     rh:setmodulevalue("Scaffold","Tower",true,"boolean")
                -- else
                --     rh:setmodulevalue("Scaffold","Tower",false,"boolean")
                -- end
                -- if player.get_speed() == 0 then
                --     rh:setmodulevalue("Scaffold","Tower",false,"boolean")
                -- end
                -- if (yaw_segment/8%1 == 0 or yaw_segment/8%1 == 0.5) then
                --     rh:setmodulevalue("Scaffold","Tower Speed",4.71,"double")
                --     rh:setmodulevalue("Scaffold","Rotation Mode",getmodulevalue("Scaffold","Tower") and "UNCP" or "Normal","string")
                -- else
                --     rh:setmodulevalue("Scaffold","Tower Speed",4.63,"double")
                --     rh:setmodulevalue("Scaffold","Rotation Mode","UNCP","string")
                -- end 
                if input.is_key_down(57) then
                    rh:setmodulevalue("scaffold","Sprint Mode","None","string")
                    rh:setmodulevalue("scaffold","Speed Control","Smart","string")
                end
                if input.is_key_down(57) and not hypixeltowerstate and hypixeltowertick[2] <= 0 then
                    hypixeltowertick[1] = 25
                    hypixeltowertick[2] = 0
                    hypixeltowertick[3] = false
                    hypixeltowerstate = true
                end
                if hypixeltowerstate then
                    if hypixeltowertick[1] - ((yaw_segment/8%1 ~= 0.75 and yaw_segment/8%1 ~= 0.25) and 0 or 10) <= 0 then
                        hypixeltowerstate = false
                        hypixeltowertick[2] = 20
                        hypixeltowertick[3] = true
                    end
                end
                if hypixeltowertick[3] then
                    rh:setmodulevalue("scaffold","Tower","None","string")
                else
                    rh:setmodulevalue("scaffold","Tower","Hypixel","string")
                end
                if hypixeltowerstate and not input.is_key_down(57) and player.on_ground() then
                    hypixeltowerstate = false
                end
            end
            if towermode:get_string() == "Heypixel" then
                if player.get_speed() <= 0 and not rh:module_state("autotoggle") and input.is_key_down(57) then
                    player.jump()
                    player.jump()
                end
            end
            if alternativejump:get_boolean() and getmodulevalue("Scaffold","Sprint Mode") == "Alternative" and input.is_key_down(57) and tostring(player.get_motion_y()) == "-0.0784" then
                player.set_motion_y(0.42)
            end
            if smartgrimsnap:get_boolean() then
                local yaw_segment = math.floor((player.angles():get_yaw() + 11.25) / 22.5)
                rh:setmodulevalue("scaffold","GrimAC Snap Sprint",yaw_segment/8%1 ~= 0.25 and yaw_segment/8%1 ~= 0.75,"boolean")
            end
        end
    end
    function on_pre_motion(pre)
        if client.nullCheck() then
            bps = math.sqrt(math.pow(prevpos[1] - entity.get_x(player.id()),2.0) + math.pow(prevpos[2] - entity.get_z(player.id()),2.0)) * 20 * world.timer()
            prevpos = {entity.get_x(player.id()),entity.get_z(player.id())}
        end
        local mainangle = player.angles():get_yaw()
        local e = true
        local player_yaw = player.angles():get_yaw() % 360
        local yaw_segment = math.floor((player_yaw + 11.25) / 22.5)
        if module_manager.get_state("Scaffold") then
            if rotationfallcheck:get_boolean() and (player.fall_distance() >= 0.4 or player.is_in_void()) and input.is_key_down(57) == false then
                e = false
            end
            if speedenable:get_boolean() then
                player.set_speed(rh:tonumber(speed:get_string()))
            end
            if e then
                if customrotation:get_string() == "HypixelBackward" then
                    if player.on_ground() then
                        pre:set_yaw(mainangle + 180) -- backward
                        pre:set_pitch(84)
                    end
                end
                if customrotation:get_string() == "HypixelAdaptive" then
                    local rounded_yaw = math.floor(mainangle / 22.5 + 0.5) * 22.5
                    local diff = mainangle - rounded_yaw
                    if math.abs(diff) <= 6.25 then
                        pre:set_yaw(rounded_yaw + 180)
                    end
                end
                if customrotation:get_string() == "Godbridge" then
                    local player_yaw = player.angles():get_yaw() % 360
                    local yaw_segment = math.floor((player_yaw + 11.25) / 22.5)
                    local adjusted_yaw = 0
                    local k = input.is_key_down
                    if (yaw_segment%8 == 0 or yaw_segment/8%1 == 0.5) and get_left_pos()%1 >0.05 and get_left_pos()%1 <0.95 then
                        adjusted_yaw = player.angles_for_cords(minecraft_visual_pos(0,-1,-1)):get_yaw() + (get_left_pos() > math.floor(get_left_pos()+0.5) and -45 or 45)
                    else
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 - 180
                    end
                    if k(31) and ((yaw_segment%8 == 0 or yaw_segment/8%1 == 0.5) and get_left_pos()%1 >0.05 and get_left_pos()%1 <0.95) then
                        adjusted_yaw = adjusted_yaw + 180- (get_left_pos() > math.floor(get_left_pos()+0.5) and -90 or 90)
                    elseif k(31) then -- S
                        adjusted_yaw = adjusted_yaw + 180
                    end
                    if k(30) then -- A
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 - 270 - (k(17) and -45 or 0) - (k(31) and 45 or 0)
                    elseif k(32) then -- D
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 + 270 - (k(17) and 45 or 0) - (k(31) and -45 or 0)
                    end
                    pre:set_yaw(adjusted_yaw)
                end
                if customrotation:get_string() == "Novoline" then
                    pre:set_yaw(player.angles_for_cords(minecraft_visual_pos(0,-1,-0.1,true)):get_yaw())
                    pre:set_pitch(player.angles_for_cords(minecraft_visual_pos(0,-1,-0.1,true)):get_pitch())
                end
                if customrotation:get_string() == "Snap" then
                    pre:set_yaw(player.angles_for_cords(minecraft_visual_pos(0,-1,-1,false,true)):get_yaw() + 180)
                end
                if customrotation:get_string() == "Super" then
                    math.randomseed(os.clock()/os.time()*player.ticks_existed()+pre:get_y()*pre:get_z())
                    local adjusted_yaw = 0
                    local k = input.is_key_down
                    local godbridgeangle = math.random(-25,25) * math.random(-11,12)/10
                    if (yaw_segment%8 == 0 or yaw_segment/8%1 == 0.5) then
                        adjusted_yaw = player.angles_for_cords(minecraft_visual_pos(0,-1,-1,true,true)):get_yaw() + godbridgeangle
                        -- 直着
                    else
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 - 180
                        --斜着
                    end
                    if k(31) and ((yaw_segment%8 == 0 or yaw_segment/8%1 == 0.5) and get_left_pos()%1 >0.2 and get_left_pos()%1 <0.8) then
                        adjusted_yaw = adjusted_yaw + 180+ godbridgeangle 
                    elseif k(31) then -- S
                        adjusted_yaw = adjusted_yaw + 180
                    end
                    if k(30) then -- A
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 - 270 - (k(17) and -45 or 0) - (k(31) and 45 or 0)
                    elseif k(32) then -- D
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 + 270 - (k(17) and 45 or 0) - (k(31) and -45 or 0)
                    end
                    --[[
                    if k(57) and getmodulevalue("Scaffold","Tower") then
                        if (yaw_segment%8 == 0 or yaw_segment/8%1 == 0.5) and get_left_pos()%1 >0.05 and get_left_pos()%1 <0.95 then
                            adjusted_yaw = player.angles_for_cords(minecraft_visual_pos(0,-1,-1)):get_yaw() + (get_left_pos() > math.floor(get_left_pos()+0.5) and -45 or 45)
                        else
                            adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 - 180
                        end
                    end
                    ]]--
                    pre:set_yaw(adjusted_yaw)
                end
                if customrotation:get_string() == "Grim Unfair" then
                    if player.angles():get_pitch() >90 then
                        player.apply_angles(player.prev_angles())
                        lprint("Flag Detected")
                    end
                    rh:setmodulevalue("Scaffold","Movement Fix",true,"boolean")
                    if input.is_key_down(57) then
                        --local yaw_segment = math.floor((player.angles():get_yaw() + 11.25) / 22.5)
                        --rh:setmodulevalue("scaffold","GrimAC Snap Sprint",yaw_segment/8%1 ~= 0.25 and yaw_segment/8%1 ~= 0.75,"boolean")
                        rh:setmodulevalue("Scaffold","Sprint Mode","GrimAC","String")
                        module_manager.enable("strafefix")
                        if not grimunfairrotationhasjump then
                            module_manager.disable("scaffold")
                            module_manager.enable("scaffold")
                            grimunfairrotationhasjump = true
                    
                        end
                    else
                        module_manager.disable("strafefix")
                        rh:setmodulevalue("scaffold","GrimAC Snap Sprint",false,"boolean")
                        rh:setmodulevalue("strafefix","Fix Mode","Basic","string")
                        grimunfairrotationhasjump = false
                        rh:setmodulevalue("Scaffold","Sprint Mode","None","String")
                        local yaw = rh:GetfacingYaw()
                        pre:set_yaw(yaw)
                        pre:set_pitch(102)
                    end
                end
                if customrotation:get_string() == "Hypixel Unfair" then
                    local adjusted_yaw = 0
                    local k = input.is_key_down
                    if supertick == 0 then
                        supertick = 1
                    else
                        supertick = 0
                    end
                    adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25
                    if k(31) then
                        adjusted_yaw = adjusted_yaw + 180
                    end
                    if k(30) then -- A
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 - 90 - (k(17) and -45 or 0) - (k(31) and 45 or 0)
                    elseif k(32) then -- D
                        adjusted_yaw = math.floor((player_yaw) / 11.25 + 0.5) * 11.25 + 90 - (k(17) and 45 or 0) - (k(31) and -45 or 0)
                    end

                    pre:set_yaw(player.angles():get_yaw())
                    local pitchtest = player.angles_for_cords(minecraft_visual_pos(0,-1,input.is_key_down(57) and 0 or -0.1,true)):get_pitch()
                    pre:set_pitch(45 + pitchtest)
                end
            else
                if customrotation:get_string() == "Grim Unfair" then
                    rh:setmodulevalue("Scaffold","Movement Fix",false,"boolean")
                end
            end
        end
        if towermode:get_string() == "Moon Lua" then
            if module_manager.get_state("scaffold") and input.is_key_down(57) and player.moveInput():move_forward() == 1 then
                moonluatower = true
                moonluatowerticks = moonluatowerticks == 3 and 0 or moonluatowerticks + 1
                if player.on_ground() then
                    moonluatowerticks = 0
                end
                local pos = player.position()
                player.set_motion_y(0.41965)
                if moonluatowerticks == 1 then
                    player.set_motion_y(0.33)
                end
                if moonluatowerticks == 2 then
                    player.set_motion_y(1 - pos:get_y() % 1)
                end
                if moonluatowerticks == 3 then
                    moonluatowerticks = 0
                end
            end
            if moonluatowerticks >= 3 then
                moonluatowerticks = 0
            end
            if moonluatower and (not input.is_key_down(57) or not input.is_key_down(17)) then
                player.set_motion_y(0)
                moonluatowerticks = 0
                moonluatower = false
            end
        end
        if rh:module_state("autotoggle") then
            if safepitchenable:get_boolean() then
                if module_manager.get_state("scaffold") then
                    safepitch = pre:get_pitch()
                else
                    pre:set_pitch(safepitch)
                end
            end
            if player.on_ground() and ((autojump:get_string() == "OnEdge" and player.is_on_edge() and player.is_moving()) or (autojump:get_string() == "Normal" and player.moveInput():move_forward() == 1)) then
                player.jump()
            end
            if autojump:get_string() == "Parkour" then
                module_manager.enable("Parkour")
            end
            if autotogglemode:get_string() == "Normal" then
                if tostring(player.get_motion_y()) == "-0.0784" and player.on_ground() then
                    module_manager.disable("Scaffold")
                else
                    module_manager.enable("Scaffold")
                end
            end
            if autotogglemode:get_string() == "OnFalldown" then
                module_manager.set_state("Scaffold",not (player.fall_distance() == 0))
            end
            if autotogglemode:get_string() == "Speed" then
                if player.on_ground() then
                    module_manager.enable("Speed")
                    module_manager.disable("Scaffold")
                else
                    module_manager.enable("Scaffold")
                end
            end
            if autotogglemode:get_string() == "ReEnable" then
                if tick == 0 then
                    module_manager.enable("Scaffold")
                    tick = 1
                else
                    module_manager.disable("Scaffold")
                    tick = 0
                end
            end
            if autotogglemode:get_string() == "Heypixel Telly" then
                --rh:setmodulevalue("scaffold","sprint mode","None","string")
                if tostring(player.get_motion_y()) == "-0.0784" and player.on_ground() and not player.is_on_edge() then
                    heypixeltellygroundstate = input.is_key_down(57)
                end
                -- local _,msg = pcall(function() return unsafe.get("http://127.0.0.1:14524/api/setValue?module=Scaffold&property=Movement&sub_property=Telly&value=" .. tostring(heypixeltellygroundstate)) end)
                -- if string.find(msg,"Read timed out") ~= nil then
                --     lprint("Error: " .. msg .. " -- 无法请求Rest API修改Scaffold参数,为防止游戏未响应已自动关闭模块")
                --     module_manager.disable(getName())
                --     module_manager.disable("autotoggle")
                -- end
                if tostring(player.get_motion_y()) == "-0.0784" and player.on_ground() then
                    heypixeltellytick = 0
                    module_manager.disable("Scaffold")
                    if player.is_on_edge() then
                        rh:java_pressKey("SPACE")
                    end
                else
                    if player.fall_distance() < 0 then
                        rh:java_pressKey("SPACE",true)
                    end
                    if heypixeltellytick == 0 then
                        module_manager.enable("Scaffold")
                    end
                end
            end
            if autotogglemode:get_string() == "Quick macro" then
                if quickmacrotellytick >= 3 then
                    module_manager.enable("scaffold")
                else
                    module_manager.disable("scaffold")
                end
            end
        end
        if disablelockytick > 0 then
            player.set_motion_y(0)
        end
        if module_manager.get_state("Scaffold")  or (safepitchenable:get_boolean() and rh:module_state("autotoggle") or not safepitchenable:get_boolean()) then -- Flag Detected
            if (flagdetect_lastpreangle[1] == player.prev_angles():get_yaw() and flagdetect_lastpreangle[2] == player.prev_angles():get_pitch()) or (flagdetect_lastpreangle[1] == player.angles():get_yaw() and flagdetect_lastpreangle[2] == player.angles():get_pitch()) then
                player.set_angles(flagdetect_lastppreangle[1],flagdetect_lastppreangle[2])
                lprint("Flag detected")
            end
            flagdetect_lastpreangle = {pre:get_yaw(),pre:get_pitch()}
            flagdetect_lastppreangle = {player.angles():get_yaw(),player.angles():get_pitch()}
        end
        return pre
    end
    function on_player_move(event)
        if towermode:get_string() == "Hypixel" and hypixeltowertick[3] and rh:module_state("scaffold") and rh:module_state("scaffoldhelper") and input.is_key_down(57) and player.on_ground() then
            event:set_y(event:get_y() - 0.42)
        end
        if towermode:get_string() == "Moon Lua" then
            if module_manager.get_state("scaffold") and input.is_key_down(57) and player.moveInput():move_forward() == 1 then
                moonluatower = true
                moonluatowerticks = moonluatowerticks == 3 and 0 or moonluatowerticks + 1
                if player.on_ground() then
                    moonluatowerticks = 0
                end
                local pos = player.position()
                player.set_motion_y(0.41965)
                player.convert_speed(event,0.312)
                if moonluatowerticks == 1 then
                    player.set_motion_y(0.33)
                end
                if moonluatowerticks == 2 then
                    player.set_motion_y(1 - pos:get_y() % 1)
                end
                if moonluatowerticks == 3 then
                    moonluatowerticks = 0
                end
            end
            if moonluatowerticks >= 3 then
                moonluatowerticks = 0
            end
            if moonluatower and (not input.is_key_down(57) or not input.is_key_down(17)) then
                player.set_motion_y(0)
                moonluatowerticks = 0
                moonluatower = false
            end
        end
        if grimunfairrotationmovefix:get_boolean() and customrotation:get_string() == "Grim Unfair" and module_manager.get_state("Scaffold") and not getmodulevalue("Scaffold","Auto Direction") and not input.is_key_down(57) then
            local function getfixXZ()
                local max = grimunfairrotationbpscheck[1] and 0.28061673 or player.get_speed()
                local f = string.lower(player.facing())
                return {f == "south" and 0 or (f == "west" and -max or (f == "north" and 0 or (f == "east" and max or 0))),f == "south" and max or (f == "west" and 0 or (f == "north" and -max or (f == "east" and 0 or 0)))}
            end

            if bps >= 5.6 and not player.is_sneaking() then
                grimunfairrotationbpscheck[1] = true
            end
            if grimunfairrotationbpscheck[1] and player.facing() ~= grimunfairrotationbpscheck[2] then
                grimunfairrotationbpscheck[1] = false
                player.set_speed(player.get_speed()/2.5)
                grimunfairrotationbpscheck[2] = player.facing()
            end
            if player.is_sneaking() or event:get_y() >= -0.05 then
                grimunfairrotationbpscheck[1] = false
            end
            local wasdfix = input.is_key_down(31) and -1 or (input.is_key_down(17) and 1 or 0)            --31 S 30 A 32 D 17 W
            event:set_x(getfixXZ()[1] *wasdfix)
            event:set_z(getfixXZ()[2]*wasdfix)
        else
            grimunfairrotationbpscheck = {false,player.facing()}
        end
        return event
    end
    function on_enable()
        math.randomseed(math.floor(os.time()))
    end
    function on_render_screen(event)
        if rh:module_state("autotoggle") and autotogglemode:get_string() == "Heypixel Telly" then
            local font = "微软雅黑"
            local text = "Slanted Telly"
            local x = math.floor(event:scaled_resolution():width()/2 - rh:shader_string_width(font,text)/2)
            local y = 35
            if player.facing() == "EAST" or player.facing() == "WEST" then
                rh:table_gradient_string(font,text,x,y,dergba(rh:getClientColor()[1]),dergba(rh:getClientColor()[2]),"Slanted_Telly_Render",15,2,10)
            else
                rh:shader_draw_string(font,text,x,y,color(188,188,188,255))
            end
        end
        if module_manager.get_state("scaffold") then
            if towerwarnning:get_boolean()then
                local rgb = rgba(255,35,25)
                if getmodulevalue("Scaffold","Tower") then
                    rgb = rgba(45,255,45)
                end
                render.draw_string("MuseoCyrl16","Tower",event:scaled_resolution():width()/2 - render.string_width("MuseoCyrl16","Tower")/2,event:scaled_resolution():height()/2 + 10,rgb)
            end
        end
    end
    function on_module_toggled(module,state)
        if module == "Scaffold" then
            if state then
                grimunfairrotationbpscheck = {false,player.facing()}
                boostspeedtick[1] = 0
                if towermode:get_string() == "Hypixel" then
                    boostspeedtick[1] = boostspeedtick[1] +1
                    hypixeltowertick = {0,8,true}
                end
            else
                --player.set_speed(0)
                if math.abs(player.position():get_y() -(entity.get_y(player.id()) - entity.get_y(player.id())%0.01)) <= 0.12 and math.abs(player.get_motion_y()) < 0.2 and player.get_speed() ~= 0 then
                    ---@diagnostic disable-next-line: cast-local-type
                    disablelockytick = rh:tonumber(disablelocky:get_string())
                end
                if customspeed:get_string() == "Boost" then
                    local function setspeed(speed)
                    --player.set_speed(speed)
                    --player.message(bps)
                    for key, value in ipairs(module_manager.get_values("Scaffold")) do
                        if value:get_name() == "First Place Speed" or value:get_name() == "Actually Speed" then
                            value:set_double(speed)
                        end
                    end
                    end
                    setspeed(rh:tonumber(customspeedspeed:get_string()))
                end
                if customrotation:get_string() == "Grim Unfair" then
                    player.set_speed(0)
                    module_manager.enable("strafefix")
                    rh:setmodulevalue("strafefix","Fix Mode","Basic","string")
                end
                if customspeed:get_string() == "Heypixel" then
                    rh:setmodulevalue("strafefix","fix mode","Basic","string")
                end
            end
        end
        if module == "Auto Toggle" then
            if not state and autotogglemode:get_string() == "Heypixel Telly" then
                rh:setmodulevalue("scaffold","sprint mode","GrimAC Semi","string")
                rh:java_pressKey("SPACE",true)
            end
        end
    end
    function on_tick()
        heypixeltellytick = math.max(heypixeltellytick - 1,0)
        --disablelockytick = input.is_key_down(57) and 0 or math.max(disablelockytick - 1,0)
        disablelockytick = math.max(disablelockytick - 1,0)
        boostspeedtick[1] = boostspeedtick[1] + ((player.get_speed() > 0 and boostspeedtick[3]) and 1 or 0)
        if scaffoldtowertoggle[1] then
            scaffoldtowertoggle[2] = scaffoldtowertoggle[2] + 1
        end
        if scaffoldtowertoggle[1] and scaffoldtowertoggle[2] >= 3 then
            rh:setmodulevalue("Scaffold","Tower",(player.facing() == "NORTH" or player.facing() == "SOUTH") and true or false,"boolean")
            scaffoldtowertoggle[1] = false
            scaffoldtowertoggle[2] = 0
        end
        if player.on_ground() then
            quickmacrotellytick = 0
        else
            quickmacrotellytick = quickmacrotellytick + 1
        end
        hypixeltowertick[1] = math.max(hypixeltowertick[1] - 1,0)
        hypixeltowertick[2] = math.max(hypixeltowertick[2] - 1,0)
    end
    function on_chat(msg)
        if utf8_sub(msg,1,1) == "." then
            local command = split(utf8_sub(msg,2)," ")
            if command[1] == "helper_config" then
                msg = ".kick a"
                rh:config_chatcheck(json_config,command,getName())
            end
        end
        return msg
    end
end
function minecraft_visual_pos(left,up,forward,dicfacing,snap)
    local facing = player.facing():lower() 
    local x,y,z = player.position():get_x(),player.position():get_y(),player.position():get_z()
    if snap then
        x,y,z = player.get_x(),player.get_y(),player.get_z()
    end
    if dicfacing then
        x,y,z = entity.get_x(player.id()),entity.get_y(player.id()),entity.get_z(player.id())
    end
    if facing == "east" then
        x = x + forward
        z = z + left
    end
    if facing == "south" then
        z = z + forward
        x = x + left
    end
    if facing == "west" then
        x = x - forward
        z = z - left
    end
    if facing == "north" then
        z = z - forward
        x = x - left
    end
    y = y + up
    return x,y,z
end
function player.get_x()
    return math.ceil(entity.get_x(player.id()))
end
function player.get_y()
    return math.ceil(entity.get_y(player.id()))
end
function player.get_z()
    return math.ceil(entity.get_z(player.id()))
end
function get_left_pos()
    local facing = player.facing():lower()
    if facing == "east" then
        return entity.get_z(player.id())
    end
    if facing == "south" then
        return -entity.get_x(player.id())
    end
    if facing == "west" then
        return -entity.get_z(player.id())
    end
    if facing == "north" then
        return entity.get_x(player.id())
    end
end
function math.Floor2(nNum, n)
    if type(nNum) == "nil" then
        return 0
    end
    local t= 1
    for i = 1, n do
        t = t / 10
    end
    return nNum - nNum%t
end
function getmodulevalue(modulename,value_)
    for key, value in ipairs(module_manager.get_values(modulename)) do
        if (value:get_name() == value_) then
            return value:get_value()
        end
    end
    return false
end

-- @Split

function getName()
    return "Auto Toggle"
end
function init_script()
    player.send_message(".bind autotoggle h")
end
function on_disable()
    module_manager.disable("scaffold")
    module_manager.disable("Parkour")
end